# Copy this content to Streamlit Cloud Secrets Management
# Go to: App Settings > Secrets > Edit Secrets

[secrets]
DB_HOST = "your_database_host_here"
DB_PORT = "5432"
DB_NAME = "your_database_name_here"
DB_USER = "your_database_username_here"
DB_PASSWORD = "your_database_password_here"
DB_SSL_MODE = "prefer"

# Example for a cloud database:
# DB_HOST = "your-postgres-server.amazonaws.com"
# DB_PORT = "5432" 
# DB_NAME = "your_database"
# DB_USER = "your_username"
# DB_PASSWORD = "your_secure_password"
# DB_SSL_MODE = "require" 